### ISSUE TITLE
CH5, CH6

### ISSUE THREAD

**Issue by kevin-el** [bmh8993/study-object#12]
### 책임 할당하기
이전장에 데이터 중심 설계의 문제를 해결하는 방법 -> 책임에 초첨 맞추기

#### GRASP 패턴
1. 선제적으로 도메인에 대한 대략적인 모습 그리기 
2. 정보 전문가. 
3. 높은 응집도, 낮은 결합도 
4. 창조자 패턴

**Comment by kevin-el** [comment]
### 메시지와 인터페이스

“메세지와 인터페이스” 
- 클래스가 중요한 것은 맞지만, 클래스에만 집중하다 보면 유연한 앱이 만들어 질 수 없다. -> 유연하지 못 한 설계에 다다를 수 있다. 

훌륭한 객체지향의 필수 
- 클래스가 아닌 객체를 지향해야 한다. -> 협력안에서 객체가 가지는 책임에 집중을 해야 한다. 
- 객채지향의 가장 중요한 재료는 클래스가 아니라 “메세지” 이다. 
- 정적인 클래스 중심 적인 사고에서 동적인 “메시지” 적 사고로 전환하자 
- 구성은 클래스 , 정의는 메세지 

협력과 메세지 
- 협력의 시작 : 어떤 객체가 다른 객체에게 요청을 날릴 때 시작 
- 메세지 : 객체 사이의 협력을 가능케 하는 매개체 , 객체가 다른 객체에 접근하기 위한 유일한 방법 
- 전통적인 메타포 [서버 — 클라이언트], 클라이언트가 서버에게 요청하는 단방향 통신으로 나타낼 수 있음 
- 메세지의 정의 : 객체들이 협력 하기 위해 사용할 수 있는 유일한 의사소통 수단 -> 인터페이스, 추상화된 함수 
- 메서드 
    - 메세지를 수신했을 때 실제로 실행되는 함수 또는 프로시저 
- 메세지, 메서드 개념을 통하여서 메세지 수신자와 송신자가 느슨한 관계를 유지 할 수 있다. -> 실행 시점에 바인딩하는 메커니즘은 두 객체의 결합도를 낮춤으로써 유연학 확장성 있는 코드를 작성할 수있다. 

퍼블릭 인터페이스 
- 객체와 의사소통을 위해서 외부에 보여주는 메세지의 집합을 퍼블릭 인터페이스라고 함 
- 퍼블릭 인터페이스에 포함된 메세지 -> 오퍼레이션 -> 오퍼레이션은 구현이 아닌 추상화 
- 시그니처 = 오퍼레이션의 이름 + 파라미터 몸록 
- 오퍼레이션의 관점에서의 다형성 = 동일한 오퍼레이션 호출에 대해 서로 다른 메서드들이 실행 됨 


좋은 인터페이스를 만드는 방법 
- 책임 주도 설계 방법으로 설계하고 구현하기! 
- 그리고 훌륭한 인터페이스들이 가지는 공통된 특징 4가지 

공통된 4가지 특징 
1. 디미터 법칙
    1. 객체간의 결합도가 너무 높은 경우 사용하는 규칙 디미터 법칙 
    2. 협력 경로를 제한 함으로 결합도를 효과적으로 낮출 수 있음 (ex: 도트는 한번만 찍어라 )
    3. 부끄럼 타는 코드 
    4. 기차 충돌 
2. 묻지 말고 시켜라
    1. 훌류안 메세지는 객체의 상태를 묻지 말고, 원하는 것을 시키는 것 
    2. 밀접하게 연관된 정보와 행동을 함께 가지는 객체를 만들 수 있다. 
    3. 상태를 묻지 말고 시키자 
    4. 훌륭한 인터페이스는 객체가 어떻게 작업을 수행하는지를 노출해서는 안된다. 인터페이스는 객체가 어떻게 하는지가 아니라 무엇을 하는지 서술 해야 한다. 
3. 의도를 드러내는 인터페이스 
    1. 어떻게 -> 소통하기 어려움, 구현까지 봐야함, 메서드단의 추상화가 안됨 코드 많이 고쳐야 됨 ,”내부 구현을 설명하는 이름”
    2. 무엇을 -> 객체가 협력안에서 가져야 하는 책임을 중점으로 두고 이름을 지어야 함 
4. 명령 - 쿼리 분리 
    1. 명령 : 상태의 변경 
    2. 쿼리 : 상태 값을 출력
    3. 장점
        - 참조 투명성

**Comment by bmh8993** [comment]
메시지
- 객체들이 협력하기 위해 사용할 수 있는 유일한 의사소통 수단
- = 오퍼레이션 명 + 인자
- 메시지 송신자는 메시지로 의도만 정확하게 전달하면 된다. 처리는 수신자가 스스로 결정한다.
- 외부에 공개하는 메시지의 집합을 '퍼블릭 인터페이스'라고 한다.
- 코드관점에서 메시지는 메서드이다.
- 메시지를 결정하고, 메시지를 처리할 수신자를 결정한다. 수신자는 정보 전문가.


퍼블릭 인터페이스를 품질을 위해서 다음과 같은 원칙과 기법을 언급할 수 있음
- 디미터 법칙
- 묻지 말고 시켜라
- 의도를 드러내는 인터페이스
- 명령-쿼리 분리

디미터 법칙
- 객체의 내부 구조에 강하게 결합되지 않도록 협력 경로를 제한하라.
- 디미터 법칙을 따느는 코드는 메시지 수신자의 내부 구조가 전송자에게 노출되지 않는다.
  - good: screening.calculateMovieFee(arg)
  - bad: screening.movie.discountConditions

묻지말고 시켜라
- 객체의 외부에서 해당 객체의 상태를 기반으로 결정을 내리는 것은 객체의 캡슐화를 위반한다.

의도를 드러내는 인터페이스
- 무엇을 하는지 이름을 드러내도록 메서드의 이름을 지어야한다. 이렇게 하기 위해서는 객체가 협력안에서 수행해야하는 책임에 대해서 분명히 알아야한다.
- 추상적인 이름을 붙여라
- 결과와 목적만을 포함하도록 이름을 붙여라
- 문제를 내라. 푸는 방법에 대한 힌트를 주면 안된다.
- 협력이라는 문맥을 반영해야한다.
- 클라이언트의 의도를 표현하는 이름을 가져야한다. 즉, 클라이언트가 객체에게 무엇을 원하는지 표현해야한다.
  - ex. 영화관이 티켓 판매소에 원하는 것은 무엇인가? 티켓을 파는 것이다. 그러면 메서드의 이름은 sellTo가 되어야한다.
- 주의 사항
  - 객체의 본질을 흐리면 안된다. 객체는 하나의 책임만 가져야한다. 하나의 변경 원인만 가져야한다.

명령-쿼리 분리 원칙
- 명령: 객체의 상태를 수정하는 오퍼레이션
- 쿼리: 객체와 관련된 정보 반환하는 오퍼레이션
- 명령과 쿼리를 분리해서 부수효과를 줄일 수 있다.
- 부수효과가 발생하지 않는다는 것은 불변을 말한다.
- 명령을 하기 이전에는 쿼리의 결과가 늘 동일하다.

**Comment by bmh8993** [comment]
이전에 함수는 하나의 책임만 가져야한다고 했다. 이걸 잘못이해하고 있었다. 이건 메세지 관점에서 이해해야한다. 메세지는 분명한 의도를 가지고 있다. 즉, 그것을 구현한 메서드 역시 하나의 책임만 있어야한다.
