### ISSUE TITLE
10장 상속 

### ISSUE THREAD

**Issue by MoonSeong1000** [bmh8993/study-object#20]
Dry 원칙을 지키기 위해, 상속을 사용. 
상속을 사용하기 위해서는 부모 클래스의 구현에 대해 정확하게 이해해야 한다. 따라서 상속은 결합도를 높히게 된다.  Super 호출을 최대한 줄여야 한다.

- 불필요한 인터페이스 상속 ; vector, stack의 예는 부모의 인터페이스로 인해 자식의 규칙이 위반됨
- 메서드 오버라이딩 오작용 : instrumentedHashset의 경우 부모의 addAll도 작동하기 때문에 예상할수 없는 결과 도출
- 부모 클래스 자식 클래스의 동시 수정 문제

때문에 이러한 경우에도 추상화에 의존하도록 해야한다.
두 클래스의 차이점을 메서드로 추출해서 공통적인 부분을 만든다. 이후 부모 클래스의 코드를 자식클래스로 내리는 것보다 자식의 추상 메서드를 부모 클래스로 옮긴다

[open vs abstract](https://jslee-tech.tistory.com/m/49)

**Comment by bmh8993** [comment]
상속은 코드 재사용을 하기 위한 방법 중 하나이다.
그렇지만...
- 자식 클래스가 부모 클래스의 구현 세부사항에 의존하게 만들기 때문에 캡슐화를 약화 시킨다 > 상속은 캡슐화를 희생한다.
  - 그렇기 때문에 퍼블릭 인터페이스에 대한 고려가 필수이다. 고려하지 않는다면, 불필요한 오퍼레이션이 스며든다.
> 정말로 필요할 때에만 상속을 사용하자. 코드 재사용을 위한 방법으로 합성이 있다. 

상속의 세 가지 문제
1. 불필요한 인터페이스 상속
2. 메서드 오버라이딩의 오작용
3. 부모 클래스와 자식 클래스의 동시 수정
