### ISSUE TITLE
11, 12

### ISSUE THREAD

**Issue by bmh8993** [bmh8993/study-object#24]
10장(11장의 내용을 제대로 이해하기 위해)
- 상속은 코드 중복을 막고, 재사용성을 높이는 가장유명한 방법이다.
- 그렇지만, 결합도를 높게 만든다. 캡슐화를 희생한다.
- 그렇기때문에 정말 필요한 경우에만 상속을 사용해야한다. 
- 상속때문에 불필요한 오퍼레이션이 인터페이스에 스며든다.

11장
- 상속과 합성은 코드 재사용이라는 동일한 목적을 가지고 있다.
  - 상속은 부모 클래스의 내부 구현에 대해서 알고 있어야한다. 즉, 결합도가 높아질 수 밖에 없다.
  - 반면, 합성은 내부에 포함되는 객체의 인터페이스에 의존한다.
- 합성은 런타임에 관계가 결정된다. 더 유연한 관계를 만들 수 있다.
- 상속은 클래스 폭발 현상을 만들어낸다.

12장
- 10, 11장 결론: 코드 재사용이 목적이라면 합성을 먼저 고려하라. 상속은 타입 계층을 구조화 하기 위해 사용해야한다.(= ✅ 다형성을 가능하게 하는 타입 계층을 구축하기 위한 것이다. = 상속 계층을 정의하는 것은 메서드 탐색 경로를 정의하는 것과 같다.)
- 타입계층을 구조화한다는 것이 무엇일까? (12장의 목적이다.)
  - 다형성은 런타임에 메시지를 처리하기에 적합한 메서드를 동적으로 탐색하는 과정을 통해 구현된다.
  - 상속이 이런 메서드를 찾기 위한 일종의 탐색 경로를 클래스 계층의 형태로 구현하기 위한 방법이다.
- 상속은 코드 재사용을 목적으로 사용한다면 유지보수하기 버거운 코드가 만들어질 확률이 높다.
  - 왜? 메시지를 수신한 객체의 타입에 따라 실제로 수행하는 행동이 달라지기 때문이다.
  - 이 문맥을 결정하는 것이 수신한 객체를 가리키는 self이다.
  - 메서드 탐색은 처음에 메시지 탐색을 시작했던 self 참조가 가리키는 바로 그 클래스에서부터 다시 시작한다는 것이다. 그림 12.16을 떠올리자(418p)
  - 결론. self 전송이 깊은 상속 계층과 계층 중간중간에 함정처럼 숨겨져 있는 메서드 오버라이딩과 만나면 극단적으로 이해하기 어려운 코드가 만들어진다.
- 객체지향에서 클래스가 필수 요소가 아닌게, 프로토타입 언어 또한 메서드 오버라이딩과 같은 방식을 구현할 수 있다. (위임이 핵심이다.)
- 12장이 하고 싶은 말: 상속을 바라 볼때에 메서드 탐색 경로를 정의하는 방식이라고 바라봐야한다. 코드 재사용이 목적이 아니다.

**Comment by kevin-el** [comment]
11. 합성과 유연한 설계

상속
1. Is-a 관계
2. 상속을 통하여서 자식클래스는 부모클래스의 정의 대부분을 물려 받게 된다. 
3. 부모클래스와 다른부분만 추가하거나 재정의함으로서 기존 코드를 쉽게 확장 할 수 있다. 
4. 그러나 상속을 충분히 ㅅ활용하기 위해서는 부모클래스의 구현을 충분히 알아야 하기 때문에 부모와 자식간의 결합도가 높아 질 수 밖에 없다. -> 우아한 방법은 아님 
5. 클래스간의 정적인 관계
6. 화이트박스

합성
1. Has-a  관계
2. 합성은 구현의 의존하지 않는다는 점에서 상속과 다르다. 
3. 내부 구현이 아닌 퍼블릭 인터페이스의 의존하고 있다. 그렇기 때문에 내부 구현이 변경되더라도 영향을 최소화할 수 있다. -> 우아한 코드 
4. 클래스간의 동적인 관계
5. 블랙박스 

구현관점으로 본 상속과 합성
- 구현관점에서 합성이 상속보다 좀 더 번거롭고 복잡하게 느껴 질 수 있으나 설계는 변경과 관련된 것이라는 점을 기억하자, 변경에 유연하게 대처할 수 있는 설계가 정답일 가능성이 높다. 
- 상속은 부모클래스안에 코드를 재사용하지만 합성은 포함되어있는 퍼블릭 인터페이스를 재사용 한다. 그렇기 때문에 구현에 대한 의존성을 인터페이스에 대한 의존성으로 대체할 수 있다. 
- 높은 결합도 -> 낮은 결합도로 변경 가능 하다. 

상속에 3가지 문제점 
1. 불필요한 인터페이스 상속 -> propertise, stack
    1. 인터페이스만 상속 -> instrumentedHashSet 
2. 메서드 오버라이딩의 오작용 문제 
3. 부모 클래스와 자식클래스의 동시 수정 문제 

상속으로 인한 조합의 폭발적인 증가 
1. 하나의 기능을 추가하기 위해 불필요한 클래스들을 추가 및 수정 
2. 상속으로 인한 중복 코드의 증가 -> 클래스의 폭발, 조합의 폭발 
-> 합성으로 해결 


결론
- 코드 재사용을 위한 방법으로 상속을 사용하는 것은 썩그리 좋지 않다 -> 부모자식간의 강한 결합 


믹스인 
- 컴파일 시점에 코드를 재조합 하는 방법

**Comment by kevin-el** [comment]
> 10장(11장의 내용을 제대로 이해하기 위해)
> 
> * 상속은 코드 중복을 막고, 재사용성을 높이는 가장유명한 방법이다.
> * 그렇지만, 결합도를 높게 만든다. 캡슐화를 희생한다.
> * 그렇기때문에 정말 필요한 경우에만 상속을 사용해야한다.
> * 상속때문에 불필요한 오퍼레이션이 인터페이스에 스며든다.
> 
> 11장
> 
> * 상속과 합성은 코드 재사용이라는 동일한 목적을 가지고 있다.
>   
>   * 상속은 부모 클래스의 내부 구현에 대해서 알고 있어야한다. 즉, 결합도가 높아질 수 밖에 없다.
>   * 반면, 합성은 내부에 포함되는 객체의 인터페이스에 의존한다.
> * 합성은 런타임에 관계가 결정된다. 더 유연한 관계를 만들 수 있다.
> * 상속은 클래스 폭발 현상을 만들어낸다.
> 
> 12장
> 
> * 10, 11장 결론: 코드 재사용이 목적이라면 합성을 먼저 고려하라. 상속은 타입 계층을 구조화 하기 위해 사용해야한다.(= ✅ 다형성을 가능하게 하는 타입 계층을 구축하기 위한 것이다. = 상속 계층을 정의하는 것은 메서드 탐색 경로를 정의하는 것과 같다.)
> * 타입계층을 구조화한다는 것이 무엇일까? (12장의 목적이다.)
>   
>   * 다형성은 런타임에 메시지를 처리하기에 적합한 메서드를 동적으로 탐색하는 과정을 통해 구현된다.
>   * 상속이 이런 메서드를 찾기 위한 일종의 탐색 경로를 클래스 계층의 형태로 구현하기 위한 방법이다.
> * 상속은 코드 재사용을 목적으로 사용한다면 유지보수하기 버거운 코드가 만들어질 확률이 높다.
>   
>   * 왜? 메시지를 수신한 객체의 타입에 따라 실제로 수행하는 행동이 달라지기 때문이다.
>   * 이 문맥을 결정하는 것이 수신한 객체를 가리키는 self이다.
>   * 메서드 탐색은 처음에 메시지 탐색을 시작했던 self 참조가 가리키는 바로 그 클래스에서부터 다시 시작한다는 것이다. 그림 12.16을 떠올리자(418p)
>   * 결론. self 전송이 깊은 상속 계층과 계층 중간중간에 함정처럼 숨겨져 있는 메서드 오버라이딩과 만나면 극단적으로 이해하기 어려운 코드가 만들어진다.
> * 객체지향에서 클래스가 필수 요소가 아닌게, 프로토타입 언어 또한 메서드 오버라이딩과 같은 방식을 구현할 수 있다. (위임이 핵심이다.)
> * 12장이 하고 싶은 말: 상속을 바라 볼때에 메서드 탐색 경로를 정의하는 방식이라고 바라봐야한다. 코드 재사용이 목적이 아니다.

**Comment by kevin-el** [comment]
12장 다형성 (상속을 통한 계층 구조 및 그룹화 구현)

다형성 = 많은 (poly) + 형태 (morph) 

다형성의 종류
1. 강제다형성
2. 매개변수 다형성
3. 포함 다형성 (서브타입 다형성)

상속의 주요 매커니즘
1. 업캐스팅 : 부모 클래스의 자식 클래스 인스턴스를 할당하여 사용할 수 있다. -> 추가 확장에도 용이 무한으로 확장 간으 
4. 동적 메서드 탐색 :
5. 동적 바인딩
    1. 선언된 변수의 타입이 아니라 메세지를 수신하는 객체의 타입에 따라 실행되는 메서드가 런타임에 결정됨 (동적 바인딩, 지연바인팅)
6. Self 참조 
7. Super 참조 

이름이 비슷하여 항상 헷갈리는 개념
- 메서드 오버라이딩 -> 이름과 시그니처가 모두 같음 
- 메서드 오버로딩 -> 이름은 같으나 시그니처가 다름

상속을 바라보는 관점 
- 데이터
- 행동
