### ISSUE TITLE
ch3 역할 책임 협력

### ISSUE THREAD

**Issue by bmh8993** [bmh8993/study-object#8]
- 역할 책임 협력에 대해서 책을 보지 않고 각자 정리해보자
- kotlin에서 캡슐화는 전략은 어떤게 best practice 일까?

**Comment by bmh8993** [comment]
1. 협력: 애플리케이션 기능 구현을 위해 객체들 사이에 이루어지는 상호작용. 상태는 행동에 필요한 정보이다. 행동은 협력에 필요한 메시지이다. 거꾸로 이야기하면, 상호작용을 하는데 메시지를 사용하고, 메시지를 받아서 메서드를 사용해 용청에 응답한다. 이때 내부적으로 정의된 상태를 사용한다.
2. 책임: 객체지향에서 제일 중요한 부분이다. 메시지에 의해 객체의 책임이 결정된다. 협력에 필요한 메시지를 찾으라. 그리고 메시지를 소화할 적절한 객체를 할당하라. 적절한 객체를 할당하는 방법은 그 객체가 무엇을 아는지이다. 책임은 "요청을 수신하고, 응답을 수행하는 것"이다.
3. 역할: 배역과 배우의 관계처럼, 동일한 역할을 가진 객체들의 집합이다. 역할을 통해서 두가지 장점이 있다. 첫째는 추상화를 통한 단순화이다. 구체적인 구현을 이야기 하지 않고, 그 역할만 가지고 가볍게 이야기할 수 있다. 둘째는 설계에 유연함을 준다는 사실이다. 동일한 역할을 가졌기에 객체들이 대체될 수 있다. 하나의 연극에서 배우는 하나의 역할을 한다. 이것과 동일하게, 하나의 협력에서 객체는 하나의 역할을 한다. 그렇지만 배우는 여러 협력에서 다양한 역할을 할 수 있다. 단지 하나의 연극에서 하나의 역할만 보여진다.

책임과 역할의 차이를 한마디로 정의하면?
- 책임은 요청에 응답할 수 있는 능력이다. 역할은 동일한 능력을 가진 객체들이 차지할 수 있는 자리이다.
- 책임은 구체적이고, 역할은 추상적이다.

**Comment by bmh8993** [comment]
코틀린 캡슐화 관련 좋은 자료 공유: https://www.cs124.org/lessons/Fall2022/kotlin/053_encapsulation

**Comment by MoonSeong1000** [comment]
### 협력
- 두 객체의 상호작용을 통해 더 큰 책임을 수행하게 되며, 메시지 전송이 유일한 커뮤니케이션 수단
- 객체를 자율적으로 만들기 위해서는 내부 구현을 캡슐화 해야 한다.
- 객체의 행동은 협력이 결정하고, 상태는 행동이 결정한다.
- 결과적으로 객체가 참여하는 협력이 객체의 행동과 상태를 모두 결정한다

### 책임
- 객체에게 얼마나 적절한 책임을 주느냐가 설계의 품질을 결정한다
- 협락 안에서 책임이 외부의 인터페이스와 내부의 속성을 결정하게 된다.
- 협력을 설계하기 위해서는 책임에 초점을 맞춰야 한다 (책임주도설계)
- 캡슐화 유지를 위해 구현을 최대한 미루면서 협력에 초점을 맞춘다


### 역할
- 책임의 집합.
- 익명이 역할을 찾은 후, 그 역할을 수행할 수 있는 객체를 선택하는 방식.
- AmountDiscountPolicy, PercentDiscountPolicy -> 추상화
- 예를들어 영화 예매 협력에서 예매하라는 메세지를 처리하기 위해 객체로 Screening을 선택했다.
하나의 단계처럼 보이지만 두가지의 단계로 이루어 진것인데 하나는 영화를 예매할 수 있는 적절한 역할이 무엇인지 찾는것이고, 두번째는 역할을 수행할 객체로 Screening인스턴스를 선택하는 것 

단순하게 객체로 시작하고 반복적으로 책임과 협력을 정제해가면서 필요한 순간에 객체로부터 역할을 분리해내는 것이 가장 좋은 방법
