### ISSUE TITLE
ch4 설계 품질과 트레이트 오프

### ISSUE THREAD

**Issue by MoonSeong1000** [bmh8993/study-object#9]

**Comment by MoonSeong1000** [comment]
객체 지향 설계는 2가지 방식으로 객체를 분리할 수 있다.
1. 상태를 분할의 중심축으로
2. 책임을 분할의 중심축으로
객체를 단순 제이터의 집합으로 바라보게 된다면 내부 구현을 퍼블릭 인터페이스에 노출 시키게 되므로 설계가 변경에 취약해진다. 이런 문제를 피하기 위해서 객체의 책임에 초점을 맞춘다.

**Comment by MoonSeong1000** [comment]
데이터를 중심으로 객체를 나눴을때의 문제점
1. 캡슐화 위반
2. 높은 결합도
3. 낮은 응집도

**Comment by MoonSeong1000** [comment]
본질적으로 이른 시기에 데이터에 관해 결정하도록 한것이 패인. 책임을 중심으로 객체를 나눠야 한다. 때문에 getter, setter 메소드가 과도하게 추가되었으며, 내부 구현이 객체의 인터페이스로 그대로 노출되었다.

겍체의 행동에 초점을 맞춰서 무게중심을 객체의 내부가 아닌 외부에 맞춰지도록 하자.

**Comment by MoonSeong1000** [comment]
kotlin에서는 java처럼 get/set 메소드를 분리하지 않아도 된다.  프로퍼티 선언시 내부적으로 get/set 메소드가 모두 들어있다. 책에서 봤듯이 get/set으로 캡슐화를 어느정도 유지한것처럼 보이지만 사실 인터페이스에 필드명이 노출되어서 좋지 않은 패턴이다. 

https://kotlinlang.org/docs/properties.html#late-initialized-properties-and-variables

set 메서드로 객체의 내부의 변수를 바꾸게 된다면 객체의 불변성이 떨어진다. 따라서 copy method를 사용해서 객체를 새로 생성하는 것이 바람직한 패턴이다 (effective kotlin)

```
data class User(
	val id: Int,
	val name: String,
)

var user = User(1, "munseong")
user = user.copy(name= "zayden")
user = user.copy(name = "kevin)
```

**Comment by bmh8993** [comment]
응집도가 높다. 결합도가 낮다. = 변경 범위가 제한적이고 명확하다.
응집도가 낮다. 결합도가 높다. = 변경 범위를 파악하기 어렵다.

데이터 중심의 영화 예매시스템을 평가해보자.
- ch2에서의 구현은 주로 프로퍼티를 private 하게 관리하고 메서드를 구성하였다. 즉, 캡슐화가 잘되어 내부 구현을 노출하지 않았다.
- ch4에서의 구현은 getter/setter를 중심으로 이루어져 있다. 나의 경우 setter를 최대한 노출하지 않기위해 changeXXX와 같은 형식으로 setter를 구성했다. 그럼에도 불구하고 캡슐화가 잘 되었다고 보기는 어렵다.
  - java라고 가정했을 경우 getField, setField라고 구성하여 프로퍼티를 노출한다. kotlin의 경우 자동으로 get/set을 구성해준다고 해도 결국 해당 프로퍼티가 내부에 존재한다는 사실을 인터페이스에 노출해버린다.
  - 이는 결국 내부에 저장할 데이터에 초점을 맞췄기 때문이다.

응집도가 낮고, 결합도가 높은 구현 = ch4 = 데이터 중심의 설계
- **객체 내부 구현이 객체의 인터페이스에 드러난다는 것은 클라이언트가 구현에 강하게 결합된다는 의미이다.**
응집도가 높고, 결합도가 낮은 구현 = ch2 = 책임 중심의 설계

우리가 기억해야할 것을 상기하자면, **"협력이 결정되면, 협력에 필요한 메시지를 찾고, 메시지에 적절한 객체를 선택하는 과정이 필요하다는 것"** 이다. 불필요하게 내부 상태를 노출하는 메서드를 만들지 말자.

**객체를 구성하는데 중요한 질문이 두가지 있다.**
1. 이 객체가 어떤 데이터를 포함해야 하는가?
2. 이 객체가 데이터에 대해 수행해야 하는 오퍼레이션은 무엇인가?

**Comment by bmh8993** [comment]
여기서 고민할 거리가 생긴다. 이렇게 되면 하나의 객체안에 인터페이스들이 여럿생기지 않을까? 이건 어떻게 풀 수 있을까?
기능들이 늘어나면, 점차 Fat Model이 될 것 같다.

이걸 DDD로 풀 수 있을 것 같다. 다시 DDD 책을 읽으면 객체지향과 같이 떠오르면서 엄청난 시너지가 날 것 같은 느낌이다.

OOP
-> DDD -> TDD -> Clean Code? 이게 더 좋아보인다. 전체적인 맥락을 가져가는게 좋을 것 같다.
-> Clean Code -> TDD -> DDD?
